# Generated by Django 5.1.2 on 2024-11-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.TextField()),
                ('bg_img', models.FileField(upload_to='')),
                ('fg_img', models.FileField(upload_to='')),
                ('duraton', models.TextField()),
                ('category', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
